"""phase 0 schema

Revision ID: 22955e9aa3a2
Revises: 
Create Date: 2026-08-06 13:30:58.417576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22955e9aa3a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('broker_code', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=True),
    sa.Column('tickers_attempted', sa.Integer(), nullable=True),
    sa.Column('tickers_failed', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('yahoo_symbol', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('sub_industry', sa.Text(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.Column('board', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('trading_calendar',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('broker_flow_daily',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('broker_code', sa.Text(), nullable=False),
    sa.Column('investor_type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('buy_volume', sa.BigInteger(), nullable=True),
    sa.Column('sell_volume', sa.BigInteger(), nullable=True),
    sa.Column('buy_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('sell_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'date', 'broker_code', 'investor_type', 'source')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('ratio_from', sa.Numeric(), nullable=True),
    sa.Column('ratio_to', sa.Numeric(), nullable=True),
    sa.Column('cash_amount', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices_daily',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('open_raw', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high_raw', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low_raw', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close_raw', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close_adj', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value_traded', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'date', 'source')
    )
    op.create_table('rumors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('heard_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_channel', sa.Text(), nullable=True),
    sa.Column('source_reliability', sa.SmallInteger(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('specificity', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_control',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'entity_id', 'role', 'valid_from')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_control')
    op.drop_table('rumors')
    op.drop_table('prices_daily')
    op.drop_table('corporate_actions')
    op.drop_table('broker_flow_daily')
    op.drop_table('trading_calendar')
    op.drop_table('securities')
    op.drop_table('ingest_runs')
    op.drop_table('entities')
    # ### end Alembic commands ###
