"""add price_discrepancies table

Revision ID: d9c93a394dbd
Revises: 8fe5fbb3ebe7
Create Date: 2026-08-08 21:29:10.199804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c93a394dbd'
down_revision: Union[str, Sequence[str], None] = '8fe5fbb3ebe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_discrepancies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('yahoo_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('idx_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('diff_abs', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('diff_ticks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_discrepancies')
    # ### end Alembic commands ###
